#include <iostream>
#include <iomanip>
#include <ros/ros.h>
#include "sensor_data/velocity_data.hpp"
#include "glog/logging.h"

namespace h_x {
    bool VelocityData::SyncData(std::deque<VelocityData, Eigen::aligned_allocator<VelocityData>>& UnsyncedData, std::deque<VelocityData, Eigen::aligned_allocator<VelocityData>>& SyncedData, const double& sync_time) {
    // std::cout << " sync_time: " << std::setprecision(15) << sync_time << std::endl;
    // LOG(INFO) << " UnsyncedData->size : F -> " << UnsyncedData.size() << std::endl;
    // for (size_t i = 0; i < UnsyncedData.size(); i++)
    // {
    //     std::cout << std::setprecision(15) << UnsyncedData.at(i).time << ", ";
    // }
    // std::cout << " " << std::endl;
    // std::cout << " " << std::endl;
    // std::cout << " " << std::endl;

    while (UnsyncedData.size() >= 2) {
        if (UnsyncedData.front().time > sync_time) {
            double dt =  UnsyncedData.front().time - sync_time;
            ROS_ERROR(" VelData_err_1: [%f, %f, %f]", UnsyncedData.front().time, sync_time, dt);
            return false;
        }
        
        if (UnsyncedData.at(1).time < sync_time) {
            UnsyncedData.pop_front();
            continue;
        }
        if (sync_time - UnsyncedData.front().time > 0.2) {
            ROS_ERROR(" VelData_err_2: time diff is large 11 ");
            UnsyncedData.pop_front();
            return false;
        }
        if (UnsyncedData.at(1).time - sync_time > 0.2) {
            ROS_ERROR(" VelData_err_3: time diff is large 22 ");
            UnsyncedData.pop_front();
            return false;
        }
        break;
    }
   
    if (UnsyncedData.size() < 2) {
        // LOG(ERROR) << " UnsyncedData->size less than 2 " << std::endl;
        if(UnsyncedData.size()) {
            double dt = UnsyncedData.front().time - sync_time;
            if(std::fabs(dt) > 0.02) {
                ROS_ERROR(" VelData_err_4: dt: %f", dt);
            }
            SyncedData.emplace_back(UnsyncedData.at(0));
            return true;
        } else {
            ROS_ERROR(" VelData_err_5: vel unsynced data is empty ...... ");
        }
        return false;
    }
        

    VelocityData front_data = UnsyncedData.at(0);
    VelocityData back_data = UnsyncedData.at(1);
    VelocityData synced_data;

    double front_scale = (back_data.time - sync_time) / (back_data.time - front_data.time);
    double back_scale = (sync_time - front_data.time) / (back_data.time - front_data.time);
    synced_data.time = sync_time;
    synced_data.linear_velocity.x = front_data.linear_velocity.x * front_scale + back_data.linear_velocity.x * back_scale;
    synced_data.linear_velocity.y = front_data.linear_velocity.y * front_scale + back_data.linear_velocity.y * back_scale;
    synced_data.linear_velocity.z = front_data.linear_velocity.z * front_scale + back_data.linear_velocity.z * back_scale;
    synced_data.angular_velocity.x = front_data.angular_velocity.x * front_scale + back_data.angular_velocity.x * back_scale;
    synced_data.angular_velocity.y = front_data.angular_velocity.y * front_scale + back_data.angular_velocity.y * back_scale;
    synced_data.angular_velocity.z = front_data.angular_velocity.z * front_scale + back_data.angular_velocity.z * back_scale;

    SyncedData.emplace_back(synced_data);

    return true;
}

void VelocityData::TransformCoordinate(Eigen::Matrix4f& transform_matrix) {
    Eigen::Matrix4d matrix = transform_matrix.cast<double>();

    Eigen::Matrix3d R = matrix.block<3,3>(0,0);
    Eigen::Vector3d t = matrix.block<3,1>(0,3);

    // get angular & linear velocities in IMU frame:
    Eigen::Vector3d w(angular_velocity.x, angular_velocity.y, angular_velocity.z);
    Eigen::Vector3d v(linear_velocity.x, linear_velocity.y, linear_velocity.z);

    // a. first, add velocity component generated by rotation:
    Eigen::Vector3d delta_v;
    delta_v(0) = w(1) * t(2) - w(2) * t(1);
    delta_v(1) = w(2) * t(0) - w(0) * t(2);
    delta_v(2) = w(0) * t(1) - w(1) * t(0);
    v += delta_v;

    // b. transform velocities in IMU frame to lidar frame:
    w = R.transpose() * w;
    v = R.transpose() * v;

    // finally:
    angular_velocity.x = w(0);
    angular_velocity.y = w(1);
    angular_velocity.z = w(2);
    linear_velocity.x = v(0);
    linear_velocity.y = v(1);
    linear_velocity.z = v(2);
}

void VelocityData::NED2ENU(void) {
    LinearVelocity linear_velocity_enu;

    linear_velocity_enu.x = +linear_velocity.y;
    linear_velocity_enu.y = +linear_velocity.x;
    linear_velocity_enu.z = -linear_velocity.z;

    linear_velocity.x = linear_velocity_enu.x;
    linear_velocity.y = linear_velocity_enu.y;
    linear_velocity.z = linear_velocity_enu.z;

    AngularVelocity angular_velocity_enu;

    angular_velocity_enu.x = +angular_velocity.y;
    angular_velocity_enu.y = +angular_velocity.x;
    angular_velocity_enu.z = -angular_velocity.z;

    angular_velocity.x = angular_velocity_enu.x;
    angular_velocity.y = angular_velocity_enu.y;
    angular_velocity.z = angular_velocity_enu.z;
}
}