# find_package(PCL 1.7 REQUIRED)
# list(REMOVE_ITEM PCL_LIBRARIES "vtkproj4")

find_package(PCL REQUIRED QUIET)
include_directories(${PCL_INCLUDE_DIRS})
list(APPEND ALL_TARGET_LIBRARIES ${PCL_LIBRARIES})